version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgresrss2
    volumes:
      - "./.postgresql-data/db:/var/lib/postgresql"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rss22xml
    restart: unless-stopped